board:
  size: 7
  classic_display: true

mcts:
  dynamic_sims_time: 4.0
  min_simulations: 2000
  c: 1.3
  epsilon: 1.0
  epsilon_decay: 0.99
  epsilon_critic: 2.0
  epsilon_decay_critic: 0.996

rl:
  num_episodes: 500
  display_game_rl: true
  display_game_rl_interval: 10
  replay_buffer_size: 2048
  mini_batch_size: 256
  save_interval: 50
  select_best_move_rl: true

ann:
  learning_rate: 0.001
  cnn_num_filters: 64
  num_res_blocks: 3
  activation_function: "relu"
  output_activation_actor: "softmax"
  output_activation_critic: "tanh"
  optimizer: "Adam"
  loss_function_actor: "categorical_crossentropy"
  loss_function_critic: "mse"
  num_epochs: 5
  bridge_features: false
  use_critic: false
  model_dir: "models/"
